ALTER SESSION SET CONTAINER = pdb1;

-- creating table space

CREATE TABLESPACE _TABLESPACE_NAME_ DATAFILE '/data/_TABLESPACE_NAME_/oradata01.dbf' 
SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED 
LOGGING PERMANENT 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT MANUAL 
FLASHBACK ON; 