-- wallet creation and opening

ALTER SYSTEM SET ENCRYPTION KEY IDENTIFIED BY "_WALLET_PASSWORD_";

ALTER SYSTEM SET WALLET OPEN IDENTIFIED BY "_WALLET_PASSWORD_";

ALTER SESSION SET CONTAINER = pdb1;

-- creating table space

CREATE TABLESPACE _TABLESPACE_NAME_ DATAFILE '/data/_TABLESPACE_NAME_/oradata01.dbf' 
SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED 
LOGGING PERMANENT 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT MANUAL 
FLASHBACK ON; 

-- add user

CREATE USER _ORA_USER_ IDENTIFIED BY _ORA_PASS_
DEFAULT TABLESPACE _TABLESPACE_NAME_ 
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT 
QUOTA UNLIMITED ON _TABLESPACE_NAME_;

-- grant user

GRANT CONNECT, DBA, RESOURCE TO _ORA_USER_ WITH ADMIN OPTION; 
ALTER USER _ORA_USER_ DEFAULT ROLE CONNECT, DBA, RESOURCE; 
GRANT 
  CREATE SESSION,
  CREATE DATABASE LINK, 
  CREATE MATERIALIZED VIEW, 
  CREATE PROCEDURE, 
  CREATE PUBLIC SYNONYM, 
  CREATE ROLE, 
  CREATE SEQUENCE, 
  CREATE SYNONYM, 
  CREATE TABLE,         
  DROP ANY TABLE,       
  CREATE TRIGGER,  
  CREATE TYPE,  
  CREATE VIEW 
  TO _ORA_USER_ WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO _ORA_USER_;