---
- hosts: all
  vars:
    description: "docker installation"
  remote_user: root
  tasks:
  - file: path="/etc/docker" state=directory
  - copy: src="templates/registry/daemon.json" dest="/etc/docker/daemon.json"
  - yum: name="docker, docker-common, docker-selinux, docker-engine" state="absent"
  - command: yum makecache fast
  - yum: name="yum-utils" state="latest"
  - command: yum-config-manager --add-repo "https://download.docker.com/linux/centos/docker-ce.repo"
  - command: yum-config-manager --enable docker-ce-edge
  - yum: name="docker-ce" state="latest"
  - systemd: name="docker" enabled="yes" masked="no"
  - service: name="docker" state="started"